const $=id=>document.getElementById(id); let csrf='', editing=null, importId=null;
const fields=[['num','Номер'],['settlementId','Поселение'],['street','Улица'],['buildingType','Тип постройки'],['surname','Фамилия'],['name','Имя'],['patronymic','Отчество'],['soslovie','Сословие'],['familyStatus','Семейное положение'],['sex','Пол'],['serviceType','Род службы'],['rank','Чин'],['position','Должность'],['servicePlace','Место службы'],['registrationPlace','Место приписки'],['area_sazh','Площадь, саж²'],['source','Источник'],['scanUrl','Ссылка на скан'],['lat','Широта'],['lng','Долгота'],['plotId','ID контура']];
async function api(path,opt={}){opt.headers={...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}; if(['POST','PATCH','DELETE'].includes(opt.method)){opt.headers['X-CSRF-Token']=csrf} const r=await fetch(path,opt); const d=await r.json().catch(()=>({})); if(!r.ok)throw new Error(d.error||r.status); return d}
async function boot(){const s=await api('/api/admin/session');if(!s.authenticated)return; document.body.classList.add('authed');$('login').classList.add('hidden');$('app').classList.remove('hidden');csrf=document.cookie.split('; ').find(x=>x.startsWith('gis_csrf='))?.split('=')[1]||''; await Promise.all([loadStats(),loadSettlements(),loadRecords(),loadPlots(),loadReleases()]);}
async function login(){try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({key:$('key').value})});csrf=document.cookie.split('; ').find(x=>x.startsWith('gis_csrf='))?.split('=')[1]||'';await boot()}catch(e){$('loginErr').textContent='Ошибка входа: '+e.message}}
async function loadStats(){const d=await api('/api/admin/stats');$('stats').textContent=`Записей: ${d.records} · Контуров: ${d.plots} · Поселений: ${d.settlements} · Публикаций: ${d.releases}`}
async function loadSettlements(){const ss=await api('/api/admin/settlements');for(const id of ['settlement','importSettlement']){$(id).innerHTML='<option value="">'+(id==='settlement'?'Все поселения':'Область не выбрана')+'</option>'+ss.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}return ss}
async function loadRecords(){const p=new URLSearchParams({q:$('q').value,settlement:$('settlement').value,limit:100});const d=await api('/api/admin/records?'+p);$('records').innerHTML=`<table class="table"><tr><th>ID</th><th>№</th><th>ФИО</th><th>Поселение</th><th>Контур</th><th></th></tr>`+d.items.map(r=>`<tr><td>${r.id}</td><td>${esc(r.num)}</td><td>${esc([r.surname,r.name,r.patronymic].filter(Boolean).join(' '))}</td><td>${esc(r.settlement)}</td><td>${r.plot_id??'—'}</td><td><button onclick="editRecord(${r.id})">Изменить</button> <button class="danger" onclick="archiveRecord(${r.id})">Архив</button></td></tr>`).join('')+'</table><p class="muted">Всего: '+d.total+'</p>'}
async function editRecord(id){const r=await api('/api/admin/records/'+id);openForm('Запись #'+id,r,'record')}
function openForm(title,data,type){editing={id:data?.id,type};$('modalTitle').textContent=title;$('form').innerHTML=fields.map(([k,l])=>{let v=data?.[k]??'';if(k==='settlementId')return `<label>${l}<select name="${k}">${[...$('settlement').options].filter(o=>o.value).map(o=>`<option value="${o.value}" ${o.value===v?'selected':''}>${o.text}</option>`).join('')}</select></label>`;return `<label>${l}<input name="${k}" value="${esc(String(v))}"></label>`}).join('');$('modal').classList.remove('hidden')}
async function saveRecord(){const data=Object.fromEntries(new FormData($('form')).entries());for(const k of ['area_sazh','lat','lng','plotId'])if(data[k]!=='')data[k]=Number(data[k]);else data[k]=null; if(editing.id)await api('/api/admin/records/'+editing.id,{method:'PATCH',body:JSON.stringify(data)});else await api('/api/admin/records',{method:'POST',body:JSON.stringify(data)});close();await loadRecords();await loadStats()}
async function archiveRecord(id){if(!confirm('Архивировать запись?'))return;await api('/api/admin/records/'+id,{method:'DELETE'});await loadRecords();await loadStats()}
async function loadPlots(){const d=await api('/api/admin/plots');$('plots').innerHTML='<table class="table"><tr><th>ID</th><th>Поселение</th><th>Ключ</th><th>Связанные записи</th><th></th></tr>'+d.items.map(p=>`<tr><td>${p.id}</td><td>${esc(p.settlement)}</td><td>${esc(p.legacy_key)}</td><td>${p.record_ids?.join(', ')||'—'}</td><td><button onclick="editPlot(${p.id})">Изменить</button></td></tr>`).join('')+'</table>'}
async function editPlot(id){const p=await api('/api/admin/plots/'+id);openPlotForm(p)}
function openPlotForm(p={}){$('modalTitle').textContent=p.id?'Контур #'+p.id:'Новый контур';editing={id:p.id,type:'plot'};$('form').innerHTML=`<label>Поселение<select name="settlementId">${[...$('settlement').options].filter(o=>o.value).map(o=>`<option value="${o.value}" ${o.value===p.settlement_id?'selected':''}>${o.text}</option>`).join('')}</select></label><label>Legacy key<input name="legacyKey" value="${esc(p.legacy_key||'')}"></label><label class="wide">GeoJSON geometry<textarea name="geometry" rows="12">${esc(JSON.stringify(p.geometry||{type:'Polygon',coordinates:[[]]},null,2))}</textarea></label><label>Широта фокуса<input name="focusLat" value="${p.focus_lat??''}"></label><label>Долгота фокуса<input name="focusLng" value="${p.focus_lng??''}"></label>`;$('modal').classList.remove('hidden')}
async function savePlot(){const f=Object.fromEntries(new FormData($('form')).entries());let geometry;try{geometry=JSON.parse(f.geometry)}catch{alert('Некорректный GeoJSON');return}f.focusLat=f.focusLat===''?null:Number(f.focusLat);f.focusLng=f.focusLng===''?null:Number(f.focusLng);f.geometry=geometry;if(editing.id)await api('/api/admin/plots/'+editing.id,{method:'PATCH',body:JSON.stringify(f)});else await api('/api/admin/plots',{method:'POST',body:JSON.stringify(f)});close();await loadPlots();await loadStats()}
async function loadReleases(){const d=await api('/api/admin/releases');$('releases').innerHTML='<table class="table"><tr><th>ID</th><th>Дата</th><th>Комментарий</th></tr>'+d.map(r=>`<tr><td>${r.id}</td><td>${r.createdAt}</td><td>${esc(r.note)}</td></tr>`).join('')+'</table>'}
async function publish(){const d=await api('/api/admin/releases',{method:'POST',body:JSON.stringify({note:$('releaseNote').value})});$('releaseNote').value='';await loadReleases();await loadStats();alert('Опубликована версия #'+d.id)}
async function validateImport(){const f=$('importFile').files[0];if(!f)return;const text=await f.text();const d=await api('/api/admin/imports',{method:'POST',body:JSON.stringify({kind:f.name.toLowerCase().endsWith('.csv')?'csv':'json',mode:$('importMode').value,settlementId:$('importSettlement').value||null,content:text})});importId=d.id;$('importReport').textContent=JSON.stringify(d.report,null,2);$('applyImport').classList.toggle('hidden',!d.canApply)}
async function applyImport(){const d=await api('/api/admin/imports/'+importId+'/apply',{method:'POST'});$('importReport').textContent=JSON.stringify(d.report,null,2);$('applyImport').classList.add('hidden');await loadRecords();await loadStats()}
function close(){$('modal').classList.add('hidden')};function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('loginBtn').onclick=login;$('search').onclick=loadRecords;$('newRecord').onclick=()=>openForm('Новая запись',{},'record');$('save').onclick=()=>editing.type==='plot'?savePlot():saveRecord();$('cancel').onclick=close;$('newPlot').onclick=()=>openPlotForm();$('refreshPlots').onclick=loadPlots;$('publish').onclick=publish;$('validateImport').onclick=validateImport;$('applyImport').onclick=applyImport;$('logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};window.editRecord=editRecord;window.archiveRecord=archiveRecord;window.editPlot=editPlot;boot();
